# -*- coding: utf-8 -*-
"""Despliegue Job_Rank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MYrDQTB-8v5QNR1g-LzPlq0pRjcLpWT

# **Despliegue**


*   Cargamos el modelo

*   Cargamos los datos futuros
*   Preparar los datos futuros


*   Aplicamos el modelo para predicción
"""

#Importamos librerías básicas
#Ayudas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

import pickle
filename= "ModeloSVM_despliegue.pkl"
modelo, labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("nuevos_registros_para_despliegue.csv")
#data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title("Predicción del Rango de trabajo dentro de la empresa")

# Entradas numéricas
Age = st.slider('Age', min_value=18, max_value=80, value=30, step=1)
Years_of_Experience = st.slider('Years_of_Experience', min_value=0, max_value=40, value=5, step=1)

# Entradas categóricas
Gender = st.selectbox('Gender', ['Male', 'Female'])
Education_Level = st.selectbox('Education_Level', ['Bachelors', 'Masters', 'PhD', "High School"])
Job_Function = st.selectbox(
    'Job_Function',
    ['Engineering_Technology', 'Data_Analytics', 'Strategic_Sales', 'Marketing',
     'Human_Resources', 'Business_Operations', 'Project_Management', 'Other'])

datos = [[Age, Gender, Education_Level, Years_of_Experience, Job_Function]]
data = pd.DataFrame(datos, columns=['Age', 'Gender', 'Education_Level', 'Years_of_Experience', 'Job_Function'])

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['Education_Level', 'Job_Function'], drop_first=False, dtype=int)
data_preparada = pd.get_dummies(data_preparada, columns=['Gender'], drop_first=True, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Normalización para los metodos Knn, RN y SVM
data_preparada[['Age', 'Years_of_Experience']] = min_max_scaler.transform(data_preparada[['Age', 'Years_of_Experience']])
data_preparada.head()

#Hacemos la predicción con el modelo
Y_fut = modelo.predict(data_preparada)
print(Y_fut)

data['Predicción']=labelencoder.inverse_transform(Y_fut)
data.head()

"""# **Predicciones**

La calidad del modelo SVM es:

Exactitud (Accuracy): 0.71
→ El modelo clasifica correctamente el 71% de los casos del conjunto de prueba, mostrando un buen desempeño general.

Precisión (Precision): 0.66
→ De todas las predicciones que el modelo marcó como correctas, el 66% realmente pertenecen a la clase correspondiente. Indica que el modelo es confiable al momento de asignar etiquetas.

Recall (Sensibilidad): 0.71
→ El modelo logra identificar correctamente el 71% de los casos reales de cada clase. Es decir, detecta la mayoría de los verdaderos positivos, aunque deja escapar algunos.

F1-Score: 0.68
→ Combina precisión y recall en una sola medida de equilibrio. Un valor de 0.68 muestra un rendimiento sólido y estable entre aciertos y omisiones.






"""

data